<a href="https://colab.research.google.com/github/USMS-FPK-IA-GI-2025/controle01-numpy-matplotlib-iris/blob/main/notebooks/controle_numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle 01 — Data Science avec NumPy et Matplotlib
**Master 1 — Intelligence Artificielle & Génie Informatique (FPK / USMS)**

Nom & Prénom :    **EL MAHI  NADIA**  
Filière :    **SIIA  , FPK**       
Année universitaire :      2025 \ 2026

---

**Règles :**
- Bibliothèques autorisées : NumPy, Matplotlib
- Toute autre bibliothèque est interdite
- Chaque question doit être traitée dans une cellule dédiée
- Chaque résultat doit être brièvement interprété


# Partie A — Importation du Dataset, Arrays, Premières Manipulations

### A1. Importation du dataset
Importez NumPy et Matplotlib.  
Chargez le fichier `iris.csv` avec `np.genfromtxt` (`delimiter=','`, `skip_header=1`).  
Stockez les données dans un array nommé `data` et affichez sa `shape`.


In [1]:
import numpy as np
import matplotlib.pyplot as plt
#Charger le fichier
data = np.genfromtxt('data/Iris.csv', delimiter=',', skip_header=1)
print(f"Dimension de notre dataset :{data.shape}")


Dimension de notre dataset :(150, 6)


### A2. Séparation des features et des espèces
Séparez :
- les 4 premières colonnes numériques dans un array `features`
- la dernière colonne (espèces) dans un array `species`
Utilisez le slicing.


In [23]:
features = data[:,1:5] #toutes les lignes et 1--> 4 colonne car 1ere colonne c'est l'ID
species = data[:,-1] # Toutes les lignes et la 4eme colonnes
#verification
print(f"Dimension de features : {features.shape}")
print(f"Dimension de species : {species.shape}")

Dimension de features : (150, 4)
Dimension de species : (150,)


### A3. Indexing
Affichez les 5 premières lignes de `features` en utilisant l’indexing.


In [17]:
#Lignes 0 --> 4
print(features[:5])
print(f"Dimension du Indexing :{features[:5].shape}")

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Dimension du Indexing :(5, 4)


### A4. Extraction d’une colonne
Créez un array `sepal_length` contenant uniquement la première colonne de `features`.  
Affichez sa `size` et son `dtype`.


In [18]:
sepal_length = features[:, 0]   #1ere colonne index 0
print(f"Num total des elements dans sepal length : {sepal_length.size}")
print(f"Type de données de sepal length : {sepal_length.size}")

Num total des elements dans sepal length : 150
Type de données de sepal length : 150


### A5. Slicing par espèce
Utilisez le slicing pour extraire les 50 premières lignes correspondant à l’espèce *Setosa*.  
Stockez-les dans `setosa_features`.


In [19]:
#Slicing 50 lignes
setosa_features = features[:50]
#Verification
print(f"Dimension de setosa_features : {setosa_features.shape}")
print(f"N elements dans setosa_features : {setosa_features.size}")

Dimension de setosa_features : (50, 4)
N elements dans setosa_features : 200


# Partie B — Statistiques Basiques et Opérations Mathématiques

### B6. Moyenne par colonne
Calculez la moyenne de chaque colonne de `features` avec `np.mean(axis=0)`.


In [31]:
moyennes_col = np.mean(features, axis=0)
print(moyennes_col)


[5.84333333 3.054      3.75866667 1.19866667]


### B7. Min et Max
Trouvez la valeur minimale et maximale de la longueur des pétales.


In [50]:
#longueur des pétales 3eme colonne dans features
petal_length=features[:,2]
min_petal=np.min(petal_length)
max_petal=np.max(petal_length)
print(f"Valeur minimale de la longueur des pétales : {min_petal}")
print(f"Valeur maximale de la longueur des pétales : {max_petal}")

Valeur minimale de la longueur des pétales : 1.0
Valeur maximale de la longueur des pétales : 6.9


### B9. Normalisation
Normalisez les longueurs des pétales en les divisant par leur maximum.
Stockez le résultat dans `normalized_petals`.


In [51]:
normalized_petals = sepal_length / max_petal
#Afficher 5 premieres lignes
print(normalized_petals[:5])

[0.73913043 0.71014493 0.68115942 0.66666667 0.72463768]


### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [9]:
# Sepal_Width se trouve dans 2eme colonne de features
somme_cumulee = np.cumsum(features[50:100, 1])
print(somme_cumulee[:10])

[ 3.2  6.4  9.5 11.8 14.6 17.4 20.7 23.1 26.  28.7]


### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [10]:
# Sepal_Width se trouve dans 2eme colonne de features
somme_cumulee = np.cumsum(features[50:100, 1])
print(somme_cumulee[:10])

[ 3.2  6.4  9.5 11.8 14.6 17.4 20.7 23.1 26.  28.7]


# Partie C — Transformations Avancées avec NumPy

### C11. Espèces uniques
Listez les espèces uniques avec `np.unique` et comptez leurs occurrences.


In [26]:
esp_uniques,n_occ=np.unique(species,return_counts=True)
print(f"Les especes uniques sont :{esp_uniques}")
print(f"Nbre d'occurences est :{n_occ}")

Les especes uniques sont :[nan]
Nbre d'occurences est :[150]


### C12. Reshape par espèce
Transformez `features` en un array de forme `(3, 50, 4)` nommé `features_by_species`.


In [27]:
#shape initial (150,4),150 = 30 x 5
features_by_species=features.reshape(3,50,4)
print(f"Dimension des features_by_species : {features_by_species.shape}")

Dimension des features_by_species : (3, 50, 4)


### C13. Concaténation
Concaténez horizontalement les moyennes par colonne avec un array de zéros.


In [38]:
zeros=np.zeros(moyennes_col.shape)
concat = np.hstack((moyennes_col,zeros))
print("Resultat de concatenation :")
concat

Resultat de concatenation :


array([5.84333333, 3.054     , 3.75866667, 1.19866667, 0.        ,
       0.        , 0.        , 0.        ])

### C14. Data cleaning (simulation)
Simulez des valeurs NaN et remplacez-les avec `np.nan_to_num`.


In [43]:
liste = np.array([5, 3, np.nan, 4, 3, np.nan, 5, 3.2, 1, 0])
liste_modifiee=np.nan_to_num(liste)
print(liste_modifiee)

[5.  3.  0.  4.  3.  0.  5.  3.2 1.  0. ]


### C15. Broadcasting
Ajoutez 1 à toutes les valeurs de la première colonne de `features`.


In [45]:
features_apres=features.copy()
features_apres[:,0] += 1
features_apres[:5]


array([[6.1, 3.5, 1.4, 0.2],
       [5.9, 3. , 1.4, 0.2],
       [5.7, 3.2, 1.3, 0.2],
       [5.6, 3.1, 1.5, 0.2],
       [6. , 3.6, 1.4, 0.2]])

### C16. np.where
Créez un array binaire indiquant si la longueur des pétales est supérieure à 4.0.


In [49]:
binaire=np.where(sepal_length>4, 1, 0)#si condition verifiée return 1
print("5 premieres lignes de sepal_length :")
print(sepal_length[:5])
print("5 premieres lignes de binaire :")
binaire[:5]

5 premieres lignes de sepal_length :
[5.1 4.9 4.7 4.6 5. ]
5 premieres lignes de binaire :


array([1, 1, 1, 1, 1])

# Partie D — Visualisation avec Matplotlib (Plots Simples)

### D17. Line plot
Line plot des longueurs des sépales pour les 50 premières fleurs.


In [ ]:
# Votre code ici


### D18. Scatter plot
Scatter plot : longueur vs largeur des pétales.


In [ ]:
# Votre code ici


### D19. Bar chart
Bar chart des moyennes des quatre caractéristiques.


In [ ]:
# Votre code ici


### D20. Histogram
Histogramme de la largeur des sépales (10 bins).


In [ ]:
# Votre code ici


### D21. Boxplot par espèce
Boxplot des longueurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie E — Visualisations Avancées

### E22. Subplots comparatifs
Deux scatter plots côte à côte : Setosa vs Versicolor.


In [ ]:
# Votre code ici


### E23. Grille 2x2
Histogrammes des 4 caractéristiques avec `plt.subplots(2,2)`.


In [ ]:
# Votre code ici


### E24. Bar chart avec error bars
Moyennes par espèce avec écart-type.


In [ ]:
# Votre code ici


### E25. Scatter coloré par espèce
Scatter plot avec couleurs par espèce.


In [ ]:
# Votre code ici


### E26. Line plot superposé
Cumsum des largeurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie F — Mini-Analyse Finale

### F27. Corrélations
Calculez la matrice de corrélation avec `np.corrcoef`.


In [ ]:
# Votre code ici


### F28. Visualisation des corrélations
Visualisez les corrélations sous forme de bar chart ou scatter.


In [ ]:
# Votre code ici


### F29. Variance par espèce
Identifiez l’espèce avec la plus grande variance globale et visualisez ses distributions.


In [ ]:
# Votre code ici


### F30. Conclusion
Rédigez une conclusion contenant **3 insights** issus de votre analyse.


1) ...
2) ...
3) ...